norminette

diff --git a/libft/Makefile b/libft/Makefile
--- a/libft/Makefile
+++ b/libft/Makefile
@@ -158,7 +158,11 @@ test: goodtests #$(SEGFAULTNAMES)
 retest: testfclean test
 
 norm:
-	$(FTPREFIX)norminette libft.h sources/*
+	$(FTPREFIX)norminette libft.h sources/* | tee norminette_log.txt && grep -q "^Error:" norminette_log.txt || true
+	$(FTPREFIX)if grep -q "^Error:" norminette_log.txt; then \
+		echo "Norminette errors found. Please fix them before running the tests."; \
+		exit 1; \
+	fi
 
 memcheck:
 	$(FTPREFIX)valgrind --leak-check=full --show-leak-kinds=all tests/test "memcheck"
